In [29]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_excel("sms-data.xls", sheetname='Sheet1')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py:188: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)

In [33]:
df

,Unnamed: 0,Slot,Address,Name,Date,Type,Body,class
0,0,NaN,+916291036486,Gourav Das,2019-02-23 Sat 15:02:06,Inbox,"Dear Customer, +916291036486 is now available ...",NaN
1,1,NaN,+916291036486,Gourav Das,2019-02-07 Thu 17:30:58,Inbox,"Dear Customer, +916291036486 is now available ...",NaN
2,2,NaN,+916291036486,Gourav Das,2019-01-20 Sun 19:37:12,Inbox,Hhehehehehahahahuhuh huhu,NaN
3,3,NaN,+916291036486,Gourav Das,2019-01-20 Sun 19:36:48,Inbox,Garite pore phn kori,NaN
4,4,NaN,+916291036486,Gourav Das,2019-01-08 Tue 23:04:05,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN
5,5,NaN,+916291401871,Dad,2019-02-25 Mon 11:12:40,Inbox,"Dear Customer, +916291401871 is now available ...",NaN
6,6,NaN,+916291401871,Dad,2019-02-16 Sat 19:07:19,Sent,Jayanta Banerjee:\n+919153640637;,NaN
7,7,NaN,+916291401871,Dad,2019-02-16 Sat 11:51:01,Inbox,"Dear Customer, You have a missed call from +91...",NaN
8,8,NaN,+916291401871,Dad,2019-02-13 Wed 10:50:54,Inbox,"Dear Customer, +916291401871 is now available ...",NaN
9,9,NaN,+916291401871,Dad,2019-01-13 Sun 10:29:27,Inbox,"Dear Customer, You have 2 missed calls from +9...",NaN
10,10,NaN,+916291401871,Dad,2018-11-23 Fri 16:21:58,Inbox,"Dear Customer, +916291401871 is now available ...",NaN
11,11,NaN,+916291401871,Dad,2018-11-23 Fri 15:46:09,Sent,Accept my invite for the Truecaller app & get ...,NaN
12,12,NaN,+916295243477,NaN,2019-02-15 Fri 13:51:46,Inbox,"Dear Customer, You have a missed call from +91...",NaN
13,13,NaN,+916307917482,NaN,2019-03-10 Sun 12:29:59,Inbox,NO GST on buying a 2/3 BHK flat at Siddha Eden...,NaN
14,14,NaN,+917003342548,NaN,2019-02-22 Fri 20:02:53,Inbox,Sokal?,NaN
15,15,NaN,+917003342548,NaN,2019-02-22 Fri 18:24:31,Sent,11 e train,NaN
16,16,NaN,+917003342548,NaN,2019-02-22 Fri 18:15:40,Inbox,Kalk kokhn jabi?,NaN
17,17,NaN,+917003342548,NaN,2019-02-22 Fri 18:15:39,Inbox,Ki korchis,NaN
18,18,NaN,+917003342548,NaN,2019-02-22 Fri 18:12:25,Inbox,Ore tor ki khobor call korlam dhorlina,NaN
19,19,NaN,+917003342548,NaN,2019-02-16 Sat 11:51:20,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN
20,20,NaN,+917003342548,NaN,2019-01-26 Sat 11:13:44,Inbox,"Dear Customer, You have a missed call from +91...",NaN
21,21,NaN,+917003342548,NaN,2019-01-25 Fri 23:39:06,Sent,Good night,NaN
22,22,NaN,+917003342548,NaN,2019-01-25 Fri 23:39:00,Inbox,Tata valo thak,NaN
23,23,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:51,Inbox,Eeeeeeeee Tata good night site jachi,NaN
24,24,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:30,Sent,Ok,NaN
25,25,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:24,Inbox,Good then Ami oi sokale er dikei korbo,NaN
26,26,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:03,Sent,Yes,NaN
27,27,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:01,Inbox,National holiday to,NaN
28,28,NaN,+917003342548,NaN,2019-01-25 Fri 23:37:55,Inbox,Kal chuti to?\n,NaN
29,29,NaN,+917003342548,NaN,2019-01-25 Fri 23:37:53,Sent,Ok so,NaN
...,...,...,...,...,...,...,...,...
2406,2406,NaN,VM-MAXFSN,NaN,2018-10-12 Fri 11:04:28,Inbox,MAX festive collection is not to be missed! Ma...,NaN
2407,2407,NaN,VM-MAXFSN,NaN,2018-09-15 Sat 09:15:22,Inbox,Pujo-r Suru Max-e. Dress up in MAX's vibrant f...,NaN
2408,2408,NaN,VM-MDLIFE,NaN,2019-01-30 Wed 15:03:58,Inbox,Medlife Offers Full Body Test Worth 2690 @just...,NaN
2409,2409,NaN,VM-MDLIFE,NaN,2019-01-27 Sun 10:34:11,Inbox,Medlife Offers Full Body Test Worth 2690 @just...,NaN
2410,2410,NaN,VM-MMTRIP,NaN,2019-02-17 Sun 12:43:24,Inbox,Your MakeMyTrip MyWallet bonus balance associ...,NaN
2411,2411,NaN,VM-MMTRIP,NaN,2019-02-15 Fri 20:40:37,Inbox,Your MakeMyTrip MyWallet bonus balance associ...,NaN
2412,2412,NaN,VM-MMTRIP,NaN,2019-02-12 Tue 17:05:42,Inbox,MakeMyTrip: Sale Alert! 3 Night stay at Price ...,NaN
2413,2413,NaN,VM-MMTRIP,NaN,2019-02-10 Sun 08:15:00,Inbox,Your MakeMyTrip MyWallet bonus balance associ...,NaN
2414,2414,NaN,VM-MMTRIP,NaN,2019-02-06 Wed 16:31:46,Inbox,MakeMyTrip: Sale Alert! 3 Night stay at Price ...,NaN
2415,2415,NaN,VM-MMTRIP,NaN,2019-02-04 Mon 22:34:45,Inbox,Your MakeMyTrip MyWallet bonus balance associ...,NaN
2416,2416,NaN,VM-MMTRIP,NaN,2019-02-02 Sat 12:43:41,Inbox,MakeMyTrip: Sale Alert! 3 Night stay at Price ...,NaN
2417,2417,NaN,VM-MMTRIP,NaN,2019-01-14 Mon 20:30:11,Inbox,"Dear Sourav Das, how was your trip from Benga...",NaN
2418,2418,NaN,VM-MMTRIP,NaN,2019-01-13 Sun 14:44:56,Inbox,Your MakeMyTrip MyWallet bonus balance associ...,NaN
2419,2419,NaN,VM-PHONPE,NaN,2018-10-10 Wed 00:45:26,Inbox,You've paid Rs.251 to Flipkart via PhonePe fro...,DEBIT
2420,2420,NaN,VM-PHONPE,NaN,2018-09-28 Fri 13:12:05,Inbox,You've paid Rs.112 to SWIGGY via PhonePe from ...,DEBIT
2421,2421,NaN,VM-PHONPE,NaN,2018-09-22 Sat 20:11:46,Inbox,You've paid Rs.244 to SWIGGY via PhonePe from ...,DEBIT
2422,2422,NaN,VM-PHONPE,NaN,2018-09-16 Sun 13:27:49,Inbox,You've paid Rs.261 to SWIGGY via PhonePe from ...,DEBIT
2423,2423,NaN,VM-PayZap,NaN,2018-11-08 Thu 15:45:06,Inbox,Your SECRET OTP(One Time Password)for PayZapp ...,NaN
2424,2424,NaN,VM-Payzap,NaN,2019-03-09 Sat 11:18:51,Inbox,"WOW!CashBack up to Rs.3000 FOR YOU!\nTo avail,...",NaN
2425,2425,NaN,VM-Payzap,NaN,2019-03-06 Wed 18:35:01,Inbox,INSTANT 10% CashBack (Up to Rs. 250) FOR YOU!\...,NaN
2426,2426,NaN,VM-Payzap,NaN,2019-02-14 Thu 12:22:29,Inbox,Go on a Movie Date this Valentine's Day!\nGet ...,NaN
2427,2427,NaN,VM-Payzap,NaN,2019-02-06 Wed 11:29:37,Inbox,Refer & EARN!\nRefer your loved one for PayZap...,NaN
2428,2428,NaN,VM-Payzap,NaN,2018-10-01 Mon 19:41:37,Inbox,WOW! CashBack up to Rs.3000 FOR YOU!\nTo avail...,NaN
2429,2429,NaN,VM-RRBEXM,NaN,2018-11-30 Fri 14:26:30,Inbox,"Dear Candidate, \n\nYour CBT for Level 1 posts...",NaN
2430,2430,NaN,VM-SBIDGT,NaN,2019-02-24 Sun 16:41:08,Inbox,"Dear Customer, Your A/C ending with 2865 has b...",DEBIT
2431,2431,NaN,VM-WINGME,NaN,2018-09-29 Sat 12:24:21,Inbox,"Play Rummy FREE!\nRs.1,000 as Welcome Bonus\nC...",NaN
2432,2432,NaN,VM-YESBNK,NaN,2018-10-07 Sun 11:25:32,Inbox,SUCCESS,NaN
2433,2433,NaN,VM-iPaytm,NaN,2018-10-11 Thu 23:07:36,Inbox,Enter 174316 to link your Paytm wallet and all...,NaN
2434,2434,NaN,VM-iPaytm,NaN,2018-10-02 Tue 19:20:43,Inbox,"Dear Customer, you have agreed to the followin...",NaN
2435,2435,NaN,VM-iPaytm,NaN,2018-08-31 Fri 20:03:12,Inbox,We have received a Paytm login request from a ...,NaN

In [17]:
target = np.array(df['class'])

In [16]:
vectorizer = TfidfVectorizer(ngram_range=(1, 3))
vectorizer.fit(df['Body'])

label_encoder = LabelEncoder()
label_encoder.fit(list(df['class']))

LabelEncoder()

In [22]:
dataset = vectorizer.transform(df['Body']).toarray()

In [23]:
target = label_encoder.transform(target)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(dataset, target, test_size=0.50, random_state=42)

In [32]:
model = LinearSVC()
model.fit(X_train,y_train)

pred = model.predict(X_test)
print("LinearSVC accuracy : ", accuracy_score(y_test, pred, normalize=True))

LinearSVC accuracy :  0.9819376026272578

In [34]:
pred = model.predict(dataset)
df['predicted'] = label_encoder.inverse_transform(pred)

#### CLUSTERING

3 2311

,Unnamed: 0,Slot,Address,Name,Date,Type,Body,class,predicted,cluster_label
0,0,NaN,+916291036486,Gourav Das,2019-02-23 Sat 15:02:06,Inbox,"Dear Customer, +916291036486 is now available ...",NaN,nan,-1
1,1,NaN,+916291036486,Gourav Das,2019-02-07 Thu 17:30:58,Inbox,"Dear Customer, +916291036486 is now available ...",NaN,nan,-1
2,2,NaN,+916291036486,Gourav Das,2019-01-20 Sun 19:37:12,Inbox,Hhehehehehahahahuhuh huhu,NaN,nan,-1
3,3,NaN,+916291036486,Gourav Das,2019-01-20 Sun 19:36:48,Inbox,Garite pore phn kori,NaN,nan,-1
4,4,NaN,+916291036486,Gourav Das,2019-01-08 Tue 23:04:05,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN,nan,-1
5,5,NaN,+916291401871,Dad,2019-02-25 Mon 11:12:40,Inbox,"Dear Customer, +916291401871 is now available ...",NaN,nan,-1
6,6,NaN,+916291401871,Dad,2019-02-16 Sat 19:07:19,Sent,Jayanta Banerjee:\n+919153640637;,NaN,nan,-1
7,7,NaN,+916291401871,Dad,2019-02-16 Sat 11:51:01,Inbox,"Dear Customer, You have a missed call from +91...",NaN,nan,-1
8,8,NaN,+916291401871,Dad,2019-02-13 Wed 10:50:54,Inbox,"Dear Customer, +916291401871 is now available ...",NaN,nan,-1
9,9,NaN,+916291401871,Dad,2019-01-13 Sun 10:29:27,Inbox,"Dear Customer, You have 2 missed calls from +9...",NaN,nan,-1
10,10,NaN,+916291401871,Dad,2018-11-23 Fri 16:21:58,Inbox,"Dear Customer, +916291401871 is now available ...",NaN,nan,-1
11,11,NaN,+916291401871,Dad,2018-11-23 Fri 15:46:09,Sent,Accept my invite for the Truecaller app & get ...,NaN,nan,-1
12,12,NaN,+916295243477,NaN,2019-02-15 Fri 13:51:46,Inbox,"Dear Customer, You have a missed call from +91...",NaN,nan,-1
13,13,NaN,+916307917482,NaN,2019-03-10 Sun 12:29:59,Inbox,NO GST on buying a 2/3 BHK flat at Siddha Eden...,NaN,nan,-1
14,14,NaN,+917003342548,NaN,2019-02-22 Fri 20:02:53,Inbox,Sokal?,NaN,nan,-1
15,15,NaN,+917003342548,NaN,2019-02-22 Fri 18:24:31,Sent,11 e train,NaN,nan,-1
16,16,NaN,+917003342548,NaN,2019-02-22 Fri 18:15:40,Inbox,Kalk kokhn jabi?,NaN,nan,-1
17,17,NaN,+917003342548,NaN,2019-02-22 Fri 18:15:39,Inbox,Ki korchis,NaN,nan,-1
18,18,NaN,+917003342548,NaN,2019-02-22 Fri 18:12:25,Inbox,Ore tor ki khobor call korlam dhorlina,NaN,nan,-1
19,19,NaN,+917003342548,NaN,2019-02-16 Sat 11:51:20,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN,nan,-1
20,20,NaN,+917003342548,NaN,2019-01-26 Sat 11:13:44,Inbox,"Dear Customer, You have a missed call from +91...",NaN,nan,-1
21,21,NaN,+917003342548,NaN,2019-01-25 Fri 23:39:06,Sent,Good night,NaN,nan,-1
22,22,NaN,+917003342548,NaN,2019-01-25 Fri 23:39:00,Inbox,Tata valo thak,NaN,nan,-1
23,23,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:51,Inbox,Eeeeeeeee Tata good night site jachi,NaN,nan,-1
24,24,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:30,Sent,Ok,NaN,nan,-1
25,25,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:24,Inbox,Good then Ami oi sokale er dikei korbo,NaN,nan,-1
26,26,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:03,Sent,Yes,NaN,nan,-1
27,27,NaN,+917003342548,NaN,2019-01-25 Fri 23:38:01,Inbox,National holiday to,NaN,nan,-1
28,28,NaN,+917003342548,NaN,2019-01-25 Fri 23:37:55,Inbox,Kal chuti to?\n,NaN,nan,-1
29,29,NaN,+917003342548,NaN,2019-01-25 Fri 23:37:53,Sent,Ok so,NaN,nan,-1
...,...,...,...,...,...,...,...,...,...,...
70,70,NaN,+917003969055,Arulina,2019-02-10 Sun 20:50:23,Inbox,"Dear Customer, +917003969055 is now available ...",NaN,nan,0
71,71,NaN,+917003969055,Arulina,2019-02-09 Sat 20:43:16,Sent,Sono... Telegram ta install koro...,NaN,nan,-1
72,72,NaN,+917003969055,Arulina,2019-02-09 Sat 13:04:00,Inbox,"Dear Customer, +917003969055 is now available ...",NaN,nan,0
73,73,NaN,+917003969055,Arulina,2019-02-07 Thu 00:03:43,Inbox,"Dear Customer, You have 2 missed calls from +9...",NaN,nan,-1
74,74,NaN,+917003969055,Arulina,2019-02-06 Wed 11:29:49,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN,nan,-1
75,75,NaN,+917003969055,Arulina,2019-02-05 Tue 13:06:29,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN,nan,-1
76,76,NaN,+917003969055,Arulina,2019-02-05 Tue 11:18:00,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN,nan,-1
77,77,NaN,+917003969055,Arulina,2019-02-05 Tue 09:40:48,Inbox,"Dear Customer, You have 13 missed calls from +...",NaN,nan,-1
78,78,NaN,+917003969055,Arulina,2019-02-04 Mon 09:41:01,Inbox,"Dear Customer, You have 5 missed calls from +9...",NaN,nan,-1
79,79,NaN,+917003969055,Arulina,2019-02-03 Sun 00:00:33,Inbox,"Dear Customer, You have a missed call from +91...",NaN,nan,-1
80,80,NaN,+917003969055,Arulina,2019-02-01 Fri 01:30:00,Inbox,"Dear Customer, +917003969055 is now available ...",NaN,nan,0
81,81,NaN,+917003969055,Arulina,2019-01-31 Thu 23:02:36,Inbox,"Dear Customer, You have 9 missed calls from +9...",NaN,nan,-1
82,82,NaN,+917003969055,Arulina,2019-01-29 Tue 22:03:25,Inbox,"Dear Customer, You have 6 missed calls from +9...",NaN,nan,-1
83,83,NaN,+917003969055,Arulina,2019-01-27 Sun 05:11:38,Inbox,"Dear Customer, +917003969055 is now available ...",NaN,nan,0
84,84,NaN,+917003969055,Arulina,2019-01-27 Sun 02:29:43,Sent,Aro phn switched off korar kichu chilo na,NaN,nan,-1
85,85,NaN,+917003969055,Arulina,2019-01-27 Sun 02:29:23,Sent,Ora 300 chaiche,NaN,nan,-1
86,86,NaN,+917003969055,Arulina,2019-01-27 Sun 02:29:06,Sent,Ola cancle kore diyechi,NaN,nan,-1
87,87,NaN,+917003969055,Arulina,2019-01-27 Sun 02:14:24,Sent,Ota true caller,NaN,nan,-1
88,88,NaN,+917003969055,Arulina,2019-01-27 Sun 02:14:14,Sent,Eta hoche sms,NaN,nan,-1
89,89,NaN,+917003969055,Arulina,2019-01-27 Sun 02:11:53,Sent,+918100448204: Dummy sms,NaN,nan,-1
90,90,NaN,+917003969055,Arulina,2019-01-26 Sat 17:57:07,Inbox,"Dear Customer, You have 6 missed calls from +9...",NaN,nan,-1
91,91,NaN,+917003969055,Arulina,2019-01-25 Fri 00:55:35,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN,nan,-1
92,92,NaN,+917003969055,Arulina,2019-01-23 Wed 12:40:04,Sent,Telegram theke picture gulo soriye cho?,NaN,nan,-1
93,93,NaN,+917003969055,Arulina,2019-01-21 Mon 11:36:04,Inbox,"Dear Customer, You have a missed call from +91...",NaN,nan,-1
94,94,NaN,+917003969055,Arulina,2019-01-21 Mon 10:58:22,Inbox,"Dear Customer, You have a missed call from +91...",NaN,nan,-1
95,95,NaN,+917003969055,Arulina,2019-01-21 Mon 10:26:30,Inbox,"Dear Customer, You have 28 missed calls from +...",NaN,nan,-1
96,96,NaN,+917003969055,Arulina,2019-01-20 Sun 13:17:56,Inbox,"Dear Customer, +917003969055 is now available ...",NaN,nan,0
97,97,NaN,+917003969055,Arulina,2019-01-10 Thu 18:13:35,Inbox,"Dear Customer, You have a missed call from +91...",NaN,nan,-1
98,98,NaN,+917003969055,Arulina,2019-01-09 Wed 11:14:27,Inbox,"Dear Customer, You have 3 missed calls from +9...",NaN,nan,-1
99,99,NaN,+917003969055,Arulina,2019-01-09 Wed 11:14:12,Inbox,"Dear Customer, +917003969055 is now available ...",NaN,nan,0